### PR TITLE
Feature/105 eda notebook for the hillstrom dataset

### PR DESCRIPTION
**Pull request by lyutov89**
---
name: "Pull request"
about: Make changes in scikit-uplift
---

## 📑 Description of the Change

EDA notebook on top of the Hillstrom dataset in notebooks with fetch_hillstrom function.
Included points:

how to download
simple dataset EDA 
simple model fit/predict (-). Need more time to make multiclass in CatBoost. 

-->

## Verification Process

Run notebook on your PC. 

-->

## Release Notes

- EDA for general features and targets. 

-->

## Additional info
I check on github and I see there is crop boxes on correlation matrix. How to handle this?? It looks really ugly.. -->

### CODE REVIEW

**Comment by lyutov89** [comment]
commit 038bfb961edbfa78cf38478f91f26e58e14c7f11

**Comment by maks-sh** [comment]
Hey!

Thanks for your work!

Now I see two different notebooks (Hillstrom_dataset.ipynb and Hillstrom_dataset_upd.ipynb) in your branch.
Please delete one.
The notebook is better called `EDA_Hillstrom.ipynb` 👍

**Comment by lyutov89** [comment]
Hi, Maks. I've finished job. Check, please.

**Review by maks-sh — APPROVED** [review]

**Comment by maks-sh** [comment]
Nice work!

Thank you 👍 

Please do not forget to make a submission on the [ods.ai](https://ods.ai/tracks/open-source-soc2021/competitions/scikit-uplift-hack-soc2021) with a link to this PR.

**Pull request merged**
