### PR TITLE
Add new function fetch_megafon

### PR DESCRIPTION
**Pull request by ezhdi**
---
name: "Add new function fetch_megafon"
about: Add Megafon dataset in sklift.datasets described in issue #99
---

## 📑 Description of the Change

Add new function fetch_megafon in sklift.datasets that loads and return train part of the Megafon dataset

### CODE REVIEW

**Comment by maks-sh** [comment]
Hey!

Thank you 🙌  Amazing work 👍 

There are a couple of small comments:
1) Since we do not have the ability to select a target, it makes no sense to create the `target_col ' argument. The [fetch_x5](https://github.com/maks-sh/scikit-uplift/blob/master/sklift/datasets/datasets.py#L171) function is made similarly.
2) Unfortunately, now the documentation pages are not created automatically. Therefore, when adding new functions, you need to manually add a page to the desired directory. In your case, this directory is `scikit-uplift/docs/api/datasets/`. Please create a page along the way with content similar to [fetch_x5](https://raw.githubusercontent.com/maks-sh/scikit-uplift/master/docs/api/datasets/fetch_x5.rst) function.
3) It would be great to add the `Key figures` section to `descr/megafon.rst` by analogy with the [criteo dataset](https://www.uplift-modeling.com/en/latest/api/datasets/fetch_criteo.html#key-figures) (Format, Size, Rows, etc.). 

I apologize that these items were not described in the issue.

**Comment by ezhdi** [comment]
Hi! fix all and bug with import all datasets too

**Comment by ezhdi** [comment]
Add example of usages for fetch_megafon  to the docstrings

**Review by maks-sh — APPROVED** [review]

**Comment by maks-sh** [comment]
Thank you for your contribution!

Please do not forget to make a submission on the [ods.ai](https://ods.ai/tracks/open-source-soc2021/competitions/scikit-uplift-hack-soc2021) with a link to this PR.

**Pull request merged**
