### PR TITLE
Update Readme.rst

### PR DESCRIPTION
**Pull request by 00helloworld**
Fix the Tags translation in Chinese in Readme

---
name: "Pull request"
about: Make changes in scikit-uplift
---

### CODE REVIEW

**Comment by maks-sh** [comment]
Hi! 👋

Thank you so much for your contribution, a very important change! 👍 

Is it correct that the English word `uplift` should be the first tag? or is it a typo?
image

**Comment by 00helloworld** [comment]
Hi, there is no precise word or description in Chinese for `uplift` so I think it would be convenient for understanding to keep it here. 
Thanks for your repo!

**Comment by 00helloworld** [comment]
> Hi, there is no precise word or description in Chinese for `uplift` so I think it would be convenient for understanding to keep it here. Thanks for your repo!



> Hi! 👋
> 
> Thank you so much for your contribution, a very important change! 👍
> 
> Is it correct that the English word `uplift` should be the first tag? or is it a typo? image

Hi, there is no precise word or description in Chinese for uplift so I think it would be convenient for understanding to keep it here.
Thanks for your repo!

**Comment by 00helloworld** [comment]
> Hi! 👋
> 
> Thank you so much for your contribution, a very important change! 👍
> 
> Is it correct that the English word `uplift` should be the first tag? or is it a typo? image

Hi, there is no precise word or description in Chinese for uplift so I think it would be convenient for understanding to keep it here.
Thanks for your repo!

**Comment by maks-sh** [comment]
Okay, thanks for clarifying

Tags are also available on the main page of the site with documentation: `scikit-uplift/docs/index.rst`.

Could you please make changes in this file as well?

**Comment by 00helloworld** [comment]
> Okay, thanks for clarifying
> 
> Tags are also available on the main page of the site with documentation: `scikit-uplift/docs/index.rst`.
> 
> Could you please make changes in this file as well?

Changes done in this file. But some checks for this PR were not successful. I tried to fetch upstream but still check failed.

**Comment by 00helloworld** [comment]
I will close this PR because of checks failure and then open a new PR.

**Pull request closed without merging**
